### ISSUE TITLE
[FE] 웹 접근성을 향상한다.

### ISSUE THREAD

**Issue by jswith** [woowacourse-teams/2022-f12#679]
# 목표
- 웹 접근성을 향상한다.
- LightHouse 웹 접근성 항목, Storybook 웹 접근성 테스트를 활용한다.

# 주의사항(Optional)

**Comment by uk960214** [comment]
카테고리 메뉴를 오픈하면 자동으로 포커스 + 펼쳐졌다는 사실을 알려주기

**Comment by uk960214** [comment]
검색 시 결과 없으면 결과 없음 결과를 읽어주는 피드백이 없다

**Comment by uk960214** [comment]
카테고리 등 필터 버튼 선택됨-선택안됨 상태 표시

**Comment by uk960214** [comment]
제품 상세 페이지에서 그래프 영역을 알려주는 말이 있으면 좋겠다.

**Comment by wonsss** [comment]
템플릿 리터럴은 변수와 다른 스트링을 끊어서 읽히는데, 한번에 읽어주면 더 자연스러울 것 같다.

**Comment by ronci** [comment]
프로필, 사진 이미지 이름이 의미있는 이름이었으면 좋겠다.

**Comment by woose28** [comment]
상품 평가 점수에 대해 숫자만 읽어준다. 상품 점수라는 정보도 같이 읽어주면 좋겠다.
또한 댓글 개수에 대해 숫자만 읽어준다. 댓글 개수라는 정보도 읽어주면 좋겠다!

**Comment by ronci** [comment]
프로필 검색에서 어떤 버튼인지 알려줬으면 좋겠다.

**Comment by woose28** [comment]
상품 상세 페이지에서 직군별 통계 그래프에 대해서 퍼센트와 직군을 같이 읽어주면 좋겠다. 또는 퍼센트 다음에 해당 직군을 읽어주면 좋겠다.

현재는 0% 100% 0% 100% 프론트엔드 백엔드 모바일 기타 순으로 그래프를 읽어준다.

**Comment by wonsss** [comment]
nav바를 통해 메뉴 이동하면 해당 페이지의 첫 번째 요소로 포커스가 이동되면 좋겠다.

**Comment by ronci** [comment]
리뷰 많은 순 select box가 안 눌려요!

**Comment by woose28** [comment]
상품 상세 페이지의 댓글에서 점수를 포커스할 수 없다.
점수를 포커스하고 점수도 읽어주면 좋을 거 같아요.

**Comment by wonsss** [comment]
그래프를 읽을 때, 숫자와 필드명을 따로 읽는데 한번에 읽어주면 시각장애인 입장에서 그래프 이해에 도움이 될 것 같다.

**Comment by ronci** [comment]
제품 검색에서 제품을 눌렀을 때 포커스가 사라지는 문제가 있어요

**Comment by wonsss** [comment]
리뷰보기를 눌렀을 때 나오는 모달을 바로 읽어줄 수 있도록 해주면 좋을 것 같다. 현재는 모달이 최하단에 위치한 것으로 읽혀서 바로 읽히지 않아 불편한 것 같아요.

**Comment by ronci** [comment]
젠킨스 그래프에서 17%, 72%는 따로 focus되는데 6% 6%는 함께 포커스되어 같이 불러주네요!
같은 형식인데 다르게 불러줘서 예상치 못한 액션 같아요

**Comment by ronci** [comment]
연차별 통계 보기 버튼을 눌렀을 때 바뀐 그래프에 포커스가 이동했으면 좋겠어요
현제는 연차별 통계 버튼을 누르면 직군별 통계 버튼으로 바뀌면서 그 내용을 읽네요

**Comment by woose28** [comment]
프로필 페이지의 리뷰 남긴 제품에 대한 이미지에 대체 텍스트가 들어가면 좋겠다.

**Comment by ronci** [comment]
필터 버튼이 눌렸을 때 눌렸다는 정보를 알고 싶다

**Comment by ronci** [comment]
프로필 보기에서 리뷰를 작성한 제품에 대해 색상으로만 표시되어 있어서 스크린 리더기로 확인할 수가 없다

**Comment by wonsss** [comment]
리뷰작성하기 플러스 버튼에 대한 설명이 읽히면 좋겠어요. 현재는 그냥 버튼이라고만 읽히네요

**Comment by wonsss** [comment]
별점 주는 하트 버튼들에 1점 버튼 4점 버튼 등으로 요소를 읽어주면 좋을 것 같아요.

**Comment by ronci** [comment]
로그인 했을 때 모달에 뜨는 확인 버튼이 뒤의 내용을 모두 focus하고 난 후에 focus된다.

**Comment by woose28** [comment]
로그아웃 버튼을 눌렀을 때도 로그아웃 모달이 바로 포커스 되면 좋겠다!

**Comment by woose28** [comment]
로그아웃 완료 후 `로그아웃이 완료되었습니다.` 메시지를 바로 읽어주거나 로그아웃 모달로 바로 포커스가 이동하면 좋겠다.

**Comment by ronci** [comment]
선택하지 않고 선택완료를 눌렀을 시 모달이 뜨는데 사용자는 알 지 못한다.
계속 버튼의 내용을 읽어주고 왜 안넘어가는 지 알지 못하는 문제가 생긴다.

**Comment by ronci** [comment]
추가 정보를 다 입력하고 선택 완료를 눌렀을 때 안의 contents는 바뀌는 데 focus는 선택 완료 버튼만 계속 읽는다.
넘어갔는 지 안 갔는 지 사용자가 알지 못하는 문제가 있다.
안의 contents로 focus가 자동으로 이동해주었으면 좋겠다.

**Comment by woose28** [comment]
프로필 검색 페이지에서 각 유저 별로 등록한 상품을 좌우로 넘길 수 있는 버튼에 대해서 aria-label을 등록하면 좋을 거 같다.
현재는 버튼이라고만 읽어준다.
