### ISSUE TITLE
[FE] 스타일이 통일되지 않은 부분들을 통일한다.

### ISSUE THREAD

**Issue by uk960214** [woowacourse-teams/2022-f12#762]
# 목표
스타일이 통일되지 않은 일부 요소들을 찾아 통일한다.

- 버튼 여백
- 버튼 및 기타 요소 shadow

**Comment by jswith** [comment]
<img width="525" alt="스크린샷 2022-10-16 22 46 36" src="https://user-images.githubusercontent.com/64275588/196038933-bc8b9a9e-ea98-4bbd-b0d2-d57aba32cfe0.png">

아이패드 가로모드에서 nav 바 양쪽 영역이 margin 없이 딱 붙어있어요! 
이 부분도 여백을 좀 주면 좋을 것 같습니다.
