### ISSUE TITLE
[FE] 아이패드 사파리 접속 시 날짜가 NaN으로 표시된다.

### ISSUE THREAD

**Issue by jswith** [woowacourse-teams/2022-f12#767]
# 목표
날짜가 NaN으로 표시되는 문제를 해결한다.

![20221016_111136](https://user-images.githubusercontent.com/64275588/196014710-e6b6de2c-5fa5-446e-a035-a5e9e04601f7.jpg)

# 주의사항(Optional)

**Comment by uk960214** [comment]
![KakaoTalk_20221016_215954838](https://user-images.githubusercontent.com/43166681/196036788-256e7e29-003e-4652-b1f4-5c2e86bbda2b.jpg)
저는 왜 잘나오죠..?

**Comment by jswith** [comment]
공유기로 로컬 서버 접속시에만 뜨는 걸로 확인됐습니다. 이슈 닫습니다!
