### ISSUE TITLE
[FE] 스타일 관련 코드 수정

### ISSUE THREAD

**Issue by jswith** [woowacourse-teams/2022-f12#822]
# 목표
- 리뷰 작성 버튼 svg 교체
- 비로그인 사용자에게도 리뷰 작성 버튼이 보이도록 수정 (로그인 시 작성 가능하다는 모달 출력)
- 모달이 뜰 때 화면이 흔들리는 현상 수정

# 주의사항(Optional)

**Comment by uk960214** [comment]
test
